#! /bin/sh
echo "What is your url for sonarr?"
read sonarrurl

echo "What's your API Key?"
read sonarrapi

echo What directory would you like to check?
read dir

echo "How long far back do you want to go (in days)"

read days

echo Starting now. If there have been many files added, this may take a long time!


cd $dir

find . -ctime -$days -type f -iname "*.mkv" ! -iname "*.mp4" ! -iname "*.mov" -exec  checkfile.py \{\} \; > /var/log/$dir.log

curl -d '{name: "RefreshSeries"}' -H "Content-Type: application/json" -X POST $sonarrurl/api/command?apikey=$sonarrapi
wait 10
curl -d '{name: "missingEpisodeSearch"}' -H "Content-Type: application/json" -X POST $sonarrurl/api/command?apikey=$sonarrapi

echo $dir have finished. View the log at /var/log/plex-file-check/$dir.log
